inputs:
  codecov-token:
    required: true

runs:
  using: 'Composite'
  steps:
    - run: pnpm run test:unit:coverage
      shell: bash
    - uses: codecov/codecov-action@75cd11691c0faa626561e295848008c8a7dddffe # v5.5.4
      with:
        files: .coverage/coverage-final.json
        token: ${{ inputs.codecov-token }}
