inputs:
  codecov-token:
    required: true

runs:
  using: 'Composite'
  steps:
    - run: pnpm run test:unit:coverage
      shell: bash
    - uses: codecov/codecov-action@671740ac38dd9b0130fbe1cec585b89eea48d3de # v5.5.2
      with:
        files: .coverage/coverage-final.json
        token: ${{ inputs.codecov-token }}
