inputs:
  codecov-token:
    required: true

runs:
  using: 'Composite'
  steps:
    - run: pnpm run test:unit:coverage
      shell: bash
    - uses: codecov/codecov-action@fdcc8476540edceab3de004e990f80d881c6cc00 # v5.5.0
      with:
        files: .coverage/coverage-final.json
        token: ${{ inputs.codecov-token }}
