engineStrict: true
minimumReleaseAge: 1440
allowBuilds:
  '@parcel/watcher': false
  '@sentry/cli': false
  esbuild: false
  sharp: false
configDependencies:
  '@pnpm/pacquet': 0.2.6
minimumReleaseAgeExclude:
  # Renovate security update: astro@7.1.0
  - astro@7.1.0
