inputs:
  aws-access-key-id:
    required: true
  aws-secret-access-key:
    required: true
  aws-region:
    required: true
  aws-s3-bucket-name:
    required: true
  aws-s3-upload-dir:
    required: true
  aws-cloudfront-distribution:
    required: true

runs:
  using: 'Composite'
  steps:
    - uses: aws-actions/configure-aws-credentials@7474bc4690e29a8392af63c5b98e7449536d5c3a # v4.3.1
      with:
        aws-access-key-id: ${{ inputs.aws-access-key-id }}
        aws-secret-access-key: ${{ inputs.aws-secret-access-key }}
        aws-region: ${{ inputs.aws-region }}
    - run: aws s3 sync ${{ inputs.aws-s3-upload-dir }} s3://${{ inputs.aws-s3-bucket-name }} --delete --exact-timestamps
      shell: bash
    - run: aws cloudfront create-invalidation --distribution-id ${{ inputs.aws-cloudfront-distribution }} --paths "/*"
      shell: bash
