name: CMS build event

on:
  repository_dispatch:
    types: [cms_build]

env:
  MICROCMS_API_KEY: ${{ secrets.MICROCMS_API_KEY }}
  MICROCMS_SERVICE_DOMAIN: ${{ secrets.MICROCMS_SERVICE_DOMAIN }}
  GOOGLE_ADS_CLIENT: ${{ secrets.GOOGLE_ADS_CLIENT }}
  GOOGLE_ADS_SIDE_AD_SLOT_ID: ${{ secrets.GOOGLE_ADS_SIDE_AD_SLOT_ID }}
  SENTRY_DSN: ${{ secrets.SENTRY_DSN }}
  SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
  SENTRY_PROJECT_NAME: ${{ secrets.SENTRY_PROJECT_NAME }}

jobs:
  build_prod:
    runs-on: ubuntu-latest
    env:
      GA_TRACKING_ID: ${{ secrets.GA_TRACKING_ID_PROD }}
      NEW_RELIC_APP_ID: ${{ secrets.NEW_RELIC_APP_ID_PROD }}
      NEW_RELIC_ACCOUNT_ID: ${{ secrets.NEW_RELIC_ACCOUNT_ID }}
      NEW_RELIC_LICENCE_KEY: ${{ secrets.NEW_RELIC_LICENCE_KEY }}
      APP_HOST: ${{ secrets.APP_HOST_PROD }}
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - uses: ./.github/actions/init-pnpm
      - run: pnpm run build:prod
      - uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
        with:
          name: build-prod-dist
          path: dist

  deploy_prod:
    runs-on: ubuntu-latest
    needs: [build_prod]
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID_PROD }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY_PROD }}
      AWS_S3_REGION: ${{ secrets.AWS_S3_REGION_PROD }}
      AWS_S3_BUCKET_NAME: ${{ secrets.AWS_S3_BUCKET_NAME_PROD }}
      AWS_CLOUDFRONT_DISTRIBUTION: ${{ secrets.AWS_CLOUDFRONT_DISTRIBUTION_PROD }}
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - uses: actions/download-artifact@d3f86a106a0bac45b974a628896c90dbdf5c8093 # v4.3.0
        with:
          name: build-prod-dist
          path: dist
      - uses: ./.github/actions/deploy
        with:
          aws-access-key-id: ${{ env.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ env.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_S3_REGION }}
          aws-s3-bucket-name: ${{ env.AWS_S3_BUCKET_NAME }}
          aws-s3-upload-dir: dist
          aws-cloudfront-distribution: ${{ env.AWS_CLOUDFRONT_DISTRIBUTION }}
