name: Deploy check

on:
  pull_request:
    branches:
      - main

jobs:
  check_version:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        bun-version: ['1.1.39']
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/init-bun
      - uses: ./.github/actions/init-git
      - run: bunx zx ./.github/scripts/check-package-version.mjs
        shell: bash
