name: Deploy check

on:
  pull_request:
    branches:
      - main

jobs:
  check_version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/init-pnpm
      - uses: ./.github/actions/init-git
      - run: pnpm node ./.github/scripts/check-package-version.mjs
        shell: bash
