name: Deploy check

on:
  pull_request:
    branches:
      - main

env:
  BUN_VERSION: '1.1.38'

jobs:
  check_version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/init-bun
      - uses: ./.github/actions/init-git
      - run: bunx zx ./.github/scripts/check-package-version.mjs
        shell: bash
