name: Test and Build

on:
  pull_request:
    branches-ignore:
      - 'main'

env:
  MICROCMS_API_KEY: ${{ secrets.MICROCMS_API_KEY }}
  MICROCMS_SERVICE_DOMAIN: ${{ secrets.MICROCMS_SERVICE_DOMAIN }}
  SENTRY_DSN: ${{ secrets.SENTRY_DSN }}
  SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
  SENTRY_PROJECT_NAME: ${{ secrets.SENTRY_PROJECT_NAME }}

jobs:
  lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        bun-version: ['1.1.39']
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/init-bun
      - uses: ./.github/actions/lint

  unit_test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        bun-version: ['1.1.39']
    env:
      GA_TRACKING_ID: ${{ secrets.GA_TRACKING_ID_DEV }}
      NEW_RELIC_APP_ID: ${{ secrets.NEW_RELIC_APP_ID_DEV }}
      NEW_RELIC_ACCOUNT_ID: ${{ secrets.NEW_RELIC_ACCOUNT_ID }}
      NEW_RELIC_LICENCE_KEY: ${{ secrets.NEW_RELIC_LICENCE_KEY }}
      APP_HOST: ${{ secrets.APP_HOST_DEV }}
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/init-bun
      - run: bun run test:unit

  build_test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        bun-version: ['1.1.39']
    env:
      GA_TRACKING_ID: ${{ secrets.GA_TRACKING_ID_DEV }}
      NEW_RELIC_APP_ID: ${{ secrets.NEW_RELIC_APP_ID_DEV }}
      NEW_RELIC_ACCOUNT_ID: ${{ secrets.NEW_RELIC_ACCOUNT_ID }}
      NEW_RELIC_LICENCE_KEY: ${{ secrets.NEW_RELIC_LICENCE_KEY }}
      APP_HOST: ${{ secrets.APP_HOST_DEV }}
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/init-bun
      - run: bun run build:dev
      - uses: actions/upload-artifact@v4
        with:
          name: build-test-dist
          path: dist

  e2e_test:
    runs-on: ubuntu-latest
    needs: [build_test]
    strategy:
      matrix:
        bun-version: ['1.1.39']
    env:
      GA_TRACKING_ID: ${{ secrets.GA_TRACKING_ID_DEV }}
      NEW_RELIC_APP_ID: ${{ secrets.NEW_RELIC_APP_ID_DEV }}
      NEW_RELIC_ACCOUNT_ID: ${{ secrets.NEW_RELIC_ACCOUNT_ID }}
      NEW_RELIC_LICENCE_KEY: ${{ secrets.NEW_RELIC_LICENCE_KEY }}
      APP_HOST: ${{ secrets.APP_HOST_DEV }}
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/init-bun
      - uses: actions/download-artifact@v4
        with:
          name: build-test-dist
          path: dist
      - uses: bun run test:e2e
