name: Test and Build

on:
  pull_request:
    branches-ignore:
      - 'main'

env:
  MICROCMS_API_KEY: ${{ secrets.MICROCMS_API_KEY }}
  MICROCMS_SERVICE_DOMAIN: ${{ secrets.MICROCMS_SERVICE_DOMAIN }}
  GOOGLE_ADS_CLIENT: ${{ secrets.GOOGLE_ADS_CLIENT }}
  GOOGLE_ADS_SIDE_AD_SLOT_ID: ${{ secrets.GOOGLE_ADS_SIDE_AD_SLOT_ID }}
  SENTRY_DSN: ${{ secrets.SENTRY_DSN }}
  SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
  SENTRY_PROJECT_NAME: ${{ secrets.SENTRY_PROJECT_NAME }}

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - uses: ./.github/actions/pinact

  lint:
    runs-on: ubuntu-latest
    needs: [setup]
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - uses: ./.github/actions/init-pnpm
      - uses: ./.github/actions/lint

  unit_test:
    runs-on: ubuntu-latest
    needs: [setup]
    env:
      GA_TRACKING_ID: ${{ secrets.GA_TRACKING_ID_DEV }}
      NEW_RELIC_APP_ID: ${{ secrets.NEW_RELIC_APP_ID_DEV }}
      NEW_RELIC_ACCOUNT_ID: ${{ secrets.NEW_RELIC_ACCOUNT_ID }}
      NEW_RELIC_LICENCE_KEY: ${{ secrets.NEW_RELIC_LICENCE_KEY }}
      APP_HOST: ${{ secrets.APP_HOST_DEV }}
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - uses: ./.github/actions/init-pnpm
      - uses: ./.github/actions/unit-test

  build_test:
    runs-on: ubuntu-latest
    needs: [setup]
    env:
      GA_TRACKING_ID: ${{ secrets.GA_TRACKING_ID_DEV }}
      NEW_RELIC_APP_ID: ${{ secrets.NEW_RELIC_APP_ID_DEV }}
      NEW_RELIC_ACCOUNT_ID: ${{ secrets.NEW_RELIC_ACCOUNT_ID }}
      NEW_RELIC_LICENCE_KEY: ${{ secrets.NEW_RELIC_LICENCE_KEY }}
      APP_HOST: ${{ secrets.APP_HOST_DEV }}
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - uses: ./.github/actions/init-pnpm
      - run: pnpm run build:dev
      - uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
        with:
          name: build-test-dist
          path: dist
