name: Test and Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '*'

env:
  MICROCMS_API_KEY: ${{ secrets.MICROCMS_API_KEY }}
  MICROCMS_SERVICE_DOMAIN: ${{ secrets.MICROCMS_SERVICE_DOMAIN }}
  SENTRY_DSN: ${{ secrets.SENTRY_DSN }}
  SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
  SENTRY_PROJECT_NAME: ${{ secrets.SENTRY_PROJECT_NAME }}

jobs:
  lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: ['20.9']
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/init-node
      - uses: ./.github/actions/lint

  unit_test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: ['20.9']
    env:
      GA_TRACKING_ID: ${{ secrets.TEST_GA_TRACKING_ID }}
      APP_HOST: ${{ secrets.TEST_APP_HOST }}
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/init-node
      - uses: ./.github/actions/unit-test

  build_test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: ['20.9']
    env:
      GA_TRACKING_ID: ${{ secrets.TEST_GA_TRACKING_ID }}
      APP_HOST: ${{ secrets.TEST_APP_HOST }}
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/init-node
      - run: pnpm run build:dev
      - uses: actions/upload-artifact@v3
        with:
          name: build-test-dist
          path: dist

  e2e_test:
    runs-on: ubuntu-latest
    needs: [build_test]
    strategy:
      matrix:
        node-version: ['20.9']
    env:
      GA_TRACKING_ID: ${{ secrets.TEST_GA_TRACKING_ID }}
      APP_HOST: ${{ secrets.TEST_APP_HOST }}
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/init-node
      - uses: actions/download-artifact@v3
        with:
          name: build-test-dist
          path: dist
      - uses: ./.github/actions/e2e-test
