name: Deploy to production

on:
  repository_dispatch:
    types: [cms_build]

env:
  NODE_VERSION: '20.9'
  MICROCMS_API_KEY: ${{ secrets.MICROCMS_API_KEY }}
  MICROCMS_SERVICE_DOMAIN: ${{ secrets.MICROCMS_SERVICE_DOMAIN }}
  SENTRY_DSN: ${{ secrets.SENTRY_DSN }}
  SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
  SENTRY_PROJECT_NAME: ${{ secrets.SENTRY_PROJECT_NAME }}

jobs:
  build_prod:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [${{ secrets.NODE_VERSION }}]
    env:
      GA_TRACKING_ID: ${{ secrets.GA_TRACKING_ID_PROD }}
      APP_HOST: ${{ secrets.APP_HOST_PROD }}
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/init-node
      - run: pnpm run build:dev
      - uses: actions/upload-artifact@v3
        with:
          name: build-prod-dist
          path: dist

  deploy_prod:
    runs-on: ubuntu-latest
    needs: [build_prod]
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID_PROD }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY_PROD }}
      AWS_S3_REGION: ${{ secrets.AWS_S3_REGION_PROD }}
      AWS_S3_BUCKET_NAME: ${{ secrets.AWS_S3_BUCKET_NAME_PROD }}
      AWS_CLOUDFRONT_DISTRIBUTION: ${{ secrets.AWS_CLOUDFRONT_DISTRIBUTION_PROD }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/download-artifact@v3
        with:
          name: build-prod-dist
          path: dist
      - uses: ./.github/actions/deploy
        with:
          aws-access-key-id: ${{ env.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ env.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_S3_REGION }}
          aws-s3-bucket-name: ${{ env.AWS_S3_BUCKET_NAME }}
          aws-s3-upload-dir: dist
          aws-cloudfront-distribution: ${{ env.AWS_CLOUDFRONT_DISTRIBUTION }}

  create_version:
    runs-on: ubuntu-latest
    needs: [deploy_prod]
    strategy:
      matrix:
        node-version: [${{ secrets.NODE_VERSION }}]
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/init-node
      - uses: ./.github/actions/init-git
      - run: pnpm exec zx ./.github/scripts/create-version-tag.mjs
        shell: bash
